site_name: DCS Modding Documentation

theme:
    name: material
    language: en
    palette:
        scheme: slate

plugins:
  - search:
      lang:
        - en
        - tr

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - toc:
        permalink: "#"

extra_css:
  - css/extra.css

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Türkçe
      link: /tr/
      lang: tr

nav:
  - Home: index.md
  - Useful Links: links.md
  
  - Aircraft Lua:
    - Basic Principles: Aircraft/Lua/BasicPrinciples.md

    - Stubs:
      - Device Stubs: Aircraft/Lua/Stubs/DeviceStubs.md
      - Mainpanel Stubs: Aircraft/Lua/Stubs/MainPanelStubs.md
      - LockOn_Options: Aircraft/Lua/Stubs/LockOnOptions.md

    - Modules:
      - Terrain: Aircraft/Lua/Modules/Terrain.md
      - lfs: Aircraft/Lua/Modules/lfs.md
      - os: Aircraft/Lua/Modules/os.md
      - io: Aircraft/Lua/Modules/io.md
      - log: Aircraft/Lua/Modules/log.md
      - utils: Aircraft/Lua/Modules/utils.md
      - db: Aircraft/Lua/Modules/db.md
      - dictionary: Aircraft/Lua/Modules/dictionary.md
      - Weather: Aircraft/Lua/Modules/Weather.md
      - sound: Aircraft/Lua/Modules/sound.md
      - net: Aircraft/Lua/Modules/net.md
      - socket: Aircraft/Lua/Modules/socket.md
      - debug: Aircraft/Lua/Modules/debug.md
      - math: Aircraft/Lua/Modules/math.md
      - minizip: Aircraft/Lua/Modules/minizip.md

    - Devices:
      - avLuaDevice: Aircraft/Lua/Devices/avLuaDevice.md
      - avSimpleWeaponSystem: Aircraft/Lua/Devices/avSimpleWeaponSystem.md
      - avSimpleRadar: Aircraft/Lua/Devices/avSimpleRadar.md

    - Indicators:
      - Drawing: Aircraft/Lua/Indicators/drawing.md
      - Controllers: Aircraft/Lua/Indicators/controllers.md

    - Plugins:
      - NavDataPlugin: Aircraft/Lua/Plugins/NavDataPlugin.md
      - WeaponSystemPlugin: Aircraft/Lua/Plugins/WeaponSystemPlugin.md
      - LuaToolsPlugin: Aircraft/Lua/Plugins/LuaToolsPlugin.md

  - Aircraft EFM:
    - EFM API: Aircraft/EFM/EFM_API.md
    - Useful Bits: 
      - Prop Blur: Aircraft/EFM/Useful_bits/prop_blur.md

  - Database:
    - wsTypes: Database/wsTypes.md
    - iCommands: Database/iCommands.md
    - Draw Args: Database/draw-args.md

  - Useful bits:
    - Modelviewer: UsefulBits/ModelViewer.md
    - Cockpit Sounds: UsefulBits/CockpitSounds.md

  - ED Blender Exporter:
      - Overview: EDM-Export/Overview.md
      - Mesh: EDM-Export/Mesh.md
      - Materials: EDM-Export/Materials.md
      - Animations: EDM-Export/Animations.md
      - Lights: EDM-Export/Lights.md
      - Known Errors: EDM-Export/errors.md

  - Contributing: contributing.md

  - Türkçe:
    - Ana Sayfa: tr/index.md
    - Faydalı Bağlantılar: tr/links.md
  
    - Aircraft Lua:
      - Temel İlkeler: tr/Aircraft/Lua/BasicPrinciples.md

      - Stub'lar:
        - Device Stub'ları: tr/Aircraft/Lua/Stubs/DeviceStubs.md
        - Mainpanel Stub'ları: tr/Aircraft/Lua/Stubs/MainPanelStubs.md
        - LockOn_Options: tr/Aircraft/Lua/Stubs/LockOnOptions.md

      - Modüller:
        - Terrain: tr/Aircraft/Lua/Modules/Terrain.md

      - Cihazlar:
        - avLuaDevice: tr/Aircraft/Lua/Devices/avLuaDevice.md
        - avSimpleWeaponSystem: tr/Aircraft/Lua/Devices/avSimpleWeaponSystem.md
        - avSimpleRadar: tr/Aircraft/Lua/Devices/avSimpleRadar.md

      - Göstergeler:
        - Çizim: tr/Aircraft/Lua/Indicators/drawing.md
        - Kontrolcüler: tr/Aircraft/Lua/Indicators/controllers.md

      - Eklentiler:
        - NavDataPlugin: tr/Aircraft/Lua/Plugins/NavDataPlugin.md
        - WeaponSystemPlugin: tr/Aircraft/Lua/Plugins/WeaponSystemPlugin.md
        - LuaToolsPlugin: tr/Aircraft/Lua/Plugins/LuaToolsPlugin.md

    - Aircraft EFM:
      - EFM API: tr/Aircraft/EFM/EFM_API.md
      - Faydalı Notlar: 
        - Prop Blur: tr/Aircraft/EFM/Useful_bits/prop_blur.md

    - Veritabanı:
      - wsTypes: tr/Database/wsTypes.md
      - iCommands: tr/Database/iCommands.md
      - Draw Args: tr/Database/draw-args.md

    - Faydalı Notlar:
      - Modelviewer: tr/UsefulBits/ModelViewer.md
      - Kokpit Sesleri: tr/UsefulBits/CockpitSounds.md

    - ED Blender Exporter:
        - Genel Bakış: tr/EDM-Export/Overview.md
        - Mesh: tr/EDM-Export/Mesh.md
        - Materyaller: tr/EDM-Export/Materials.md
        - Animasyonlar: tr/EDM-Export/Animations.md
        - Işıklar: tr/EDM-Export/Lights.md
        - Bilinen Hatalar: tr/EDM-Export/errors.md

    - Katkıda Bulunma: tr/contributing.md
