site_name: DCS Modding Documentation

theme:
    name: material
    palette:
        scheme: slate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - toc:
        permalink: "#"

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Useful Links: links.md
  
  - Aircraft Lua:
    - Basic Principles: Aircraft/Lua/BasicPrinciples.md

    - Stubs:
      - Device Stubs: Aircraft/Lua/Stubs/DeviceStubs.md
      - Mainpanel Stubs: Aircraft/Lua/Stubs/MainPanelStubs.md
      - LockOn_Options: Aircraft/Lua/Stubs/LockOnOptions.md

    - Modules:
      - Terrain: Aircraft/Lua/Modules/Terrain.md
      - lfs: Aircraft/Lua/Modules/lfs.md
      - os: Aircraft/Lua/Modules/os.md
      - io: Aircraft/Lua/Modules/io.md
      - log: Aircraft/Lua/Modules/log.md
      - utils: Aircraft/Lua/Modules/utils.md
      - db: Aircraft/Lua/Modules/db.md
      - dictionary: Aircraft/Lua/Modules/dictionary.md
      - Weather: Aircraft/Lua/Modules/Weather.md
      - sound: Aircraft/Lua/Modules/sound.md
      - net: Aircraft/Lua/Modules/net.md
      - socket: Aircraft/Lua/Modules/socket.md
      - debug: Aircraft/Lua/Modules/debug.md
      - math: Aircraft/Lua/Modules/math.md
      - minizip: Aircraft/Lua/Modules/minizip.md

    - Devices:
      - avLuaDevice: Aircraft/Lua/Devices/avLuaDevice.md
      - avSimpleWeaponSystem: Aircraft/Lua/Devices/avSimpleWeaponSystem.md
      - avSimpleRadar: Aircraft/Lua/Devices/avSimpleRadar.md

    - Indicators:
      - Drawing: Aircraft/Lua/Indicators/drawing.md
      - Controllers: Aircraft/Lua/Indicators/controllers.md

    - Plugins:
      - NavDataPlugin: Aircraft/Lua/Plugins/NavDataPlugin.md
      - WeaponSystemPlugin: Aircraft/Lua/Plugins/WeaponSystemPlugin.md
      - LuaToolsPlugin: Aircraft/Lua/Plugins/LuaToolsPlugin.md

  - Aircraft EFM:
    - EFM API: Aircraft/EFM/EFM_API.md
    - Useful Bits: 
      - Prop Blur: Aircraft/EFM/Useful_bits/prop_blur.md

  - Database:
    - wsTypes: Database/wsTypes.md
    - iCommands: Database/iCommands.md
    - Draw Args: Database/draw-args.md

  - Useful bits:
    - Modelviewer: UsefulBits/ModelViewer.md
    - Cockpit Sounds: UsefulBits/CockpitSounds.md

  - ED Blender Exporter:
      - Overview: EDM-Export/Overview.md
      - Mesh: EDM-Export/Mesh.md
      - Materials: EDM-Export/Materials.md
      - Animations: EDM-Export/Animations.md
      - Lights: EDM-Export/Lights.md
      - Known Errors: EDM-Export/errors.md

  - Contributing: contributing.md
